# Generated by Django 2.2.4 on 2019-09-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Pid', models.AutoField(primary_key=True, serialize=False)),
                ('Pname', models.CharField(max_length=500)),
                ('Pdescription', models.CharField(max_length=3000)),
                ('Cname', models.CharField(max_length=300)),
                ('Cdetails', models.CharField(max_length=4000)),
                ('Pdeadline', models.CharField(max_length=100)),
                ('Pstartdate', models.CharField(max_length=100)),
                ('Pmanagedby', models.CharField(max_length=400)),
                ('Pcontract', models.CharField(max_length=2000)),
                ('Pimage1', models.ImageField(upload_to='media')),
                ('Pimage2', models.ImageField(upload_to='media')),
                ('Pimage3', models.ImageField(upload_to='media')),
                ('Ptextresource', models.CharField(max_length=6000)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Tid', models.AutoField(primary_key=True, serialize=False)),
                ('Pid', models.IntegerField()),
                ('Tstatus', models.IntegerField()),
                ('Ttechnology', models.CharField(max_length=4000)),
                ('Tassignedto', models.CharField(max_length=600)),
                ('Tassignedby', models.CharField(max_length=600)),
                ('Tassigneddate', models.CharField(max_length=600)),
                ('Tdeadline', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
