# Generated by Django 2.2.4 on 2019-09-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Ttitle',
            field=models.CharField(default=1, max_length=3000),
            preserve_default=False,
        ),
    ]
