# Generated by Django 2.2.4 on 2019-09-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_task_ttitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Pstatus',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
