# Generated by Django 2.2.4 on 2019-09-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_project_pstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Ttechnology',
            field=models.CharField(choices=[('JAVA', 'JAVA'), ('PYTHON', 'PYTHON'), ('MATLAB', 'MATLAB'), ('JULIA', 'JULIA'), ('R', 'R')], max_length=1),
        ),
    ]
