# Generated by Django 2.2.4 on 2019-09-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskUpdate',
            fields=[
                ('Uid', models.AutoField(primary_key=True, serialize=False)),
                ('Tid', models.CharField(max_length=300)),
                ('Utitle', models.CharField(max_length=3000)),
                ('UDtime', models.CharField(max_length=3000)),
                ('Uimg1', models.ImageField(upload_to='media')),
                ('Uimg2', models.ImageField(upload_to='media')),
                ('Uimg3', models.ImageField(upload_to='media')),
                ('Udescription', models.CharField(max_length=4000)),
                ('Uempname', models.CharField(max_length=4000)),
            ],
            options={
                'db_table': 'update',
            },
        ),
    ]
